language: haskell

ghc:
  - 7.8
  - 7.6
  - 7.4

script:
  # Option -fpedantic turns on additional wornings in addition to -Wall.
  - cabal configure --flags='pedantic data-typeable ghc-generics binary data-default deepseq' && cabal build

  # This only checks if it is able to compile without additional features,
  # unfortunately it doesn't check interaction between various build flags.
  - cabal configure --flags='pedantic -data-typeable -ghc-generics -binary -data-default -deepseq' && cabal build

  # Following line tests if sdist package is created correctly.
  - cabal sdist && cabal install dist/*.tar.gz
