# For advanced use and comprehensive documentation of the format, please see:
# http://docs.haskellstack.org/en/stable/yaml_configuration/

# (GHC 8.6.5)
resolver: lts-16.3

packages:
  - '.'

extra-deps:
  - dhall-1.33.1
  - repline-0.4.0.0
  - haskeline-0.8.0.0

flags:
  verbosity:
    binary: True
    cereal: True
    deepseq: True
    pedantic: True
    safecopy: True
    lattices: True
    dhall: True
    serialise: True
